title: Chun "Mook" Kim
description: Graphics Programmer
site_title: 'Mook Kim - Portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: MookGuyGuy
blog_url: https://mookguyguy.github.io/
email: chunmook.kim97@gmail.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 